MH-7835 Added checks for URLs in all other config.txt's When java returns protocol error, try with wget instead.
git-svn-id: https://opencast.jira.com/svn/MH/trunk@10568 e6edf6fb-f266-4316-afb4-e53d95876a76

diff --git a/docs/scripts/3rd_party/check-urls b/docs/scripts/3rd_party/check-urls
--- a/docs/scripts/3rd_party/check-urls
+++ b/docs/scripts/3rd_party/check-urls
@@ -14,6 +14,42 @@ export EPEL_MIRROR=`getmcfg EPEL_MIRROR:`
 export RPMFORGE_MIRROR=`getmcfg RPMFORGE_MIRROR:`
 export MACPORTS_SVN=`getmcfg MACPORTS_SVN:`
 #
+getcfgx() {
+  set +x
+  CFG=`awk '
+/^[     ]*'$1'/ {
+  sub("^[       ]*'$1'[         ]*", "");
+  sub("[        ]*$", "");
+  print $0
+}' $2`
+  if [ $? -ne 0 ]; then
+    set -x
+    return 1
+  fi
+  eval echo "$CFG"
+  set -x
+  return 0
+}
+#
+fetch() {
+# wget -U "$UA" --spider "$1"
+  java wget -h "$1"
+  error=$?
+  if [ $error -ne 0 ]; then
+    # Check if protocol error
+    if [ $error -eq 102 ]; then
+      # Try with wget instead
+      wget -U "$UA" --spider "$1"
+      [ $? -ne 0 ] && echo "$1" >> "$2"
+    else
+      echo "$1" >> "$2"
+    fi
+  fi
+  return 0
+}
+#
+# 1. Check master config
+#
 awk '
   /^[ 	]*[^#]+$/ {
     sub("^[ 	]*", ""); sub("[ 	]*$", "");
@@ -68,13 +104,27 @@ while [ $N -le $MAXN ]; do
   [ $? -ne 0 ] && exit 1
   # Expand mirror variables
   URL=`eval echo "$URL"`
-# wget -U "$UA" --spider "$URL"
-  java wget -h "$URL"
-  [ $? -ne 0 ] && echo "$URL" >> "$NOTFOUND"
+  fetch "$URL" "$NOTFOUND"
   N=`expr $N + 1`
 done
+#
+# 2. Check all other configs
+#
+for config in `find . -name config.txt`; do
+  URL=`getcfgx URL: $config`
+  [ -n "$URL" ] && fetch "$URL" "$NOTFOUND"
+  URL1=`getcfgx URL1: $config`
+  [ -n "$URL1" ] && fetch "$URL1" "$NOTFOUND"
+  URL2=`getcfgx URL2: $config`
+  [ -n "$URL2" ] && fetch "$URL2" "$NOTFOUND"
+  URL3=`getcfgx URL3: $config`
+  [ -n "$URL3" ] && fetch "$URL3" "$NOTFOUND"
+  URL4=`getcfgx URL4: $config`
+  [ -n "$URL4" ] && fetch "$URL4" "$NOTFOUND"
+done
+#
 if [ -s "$NOTFOUND" ]; then
-  echo "`awk 'END {print NR}' "$NOTFOUND"` URLs (out of $MAXN) not found - see file \"$NOTFOUND\""
+  echo "`awk 'END {print NR}' "$NOTFOUND"` URLs not found - see file \"$NOTFOUND\""
   exit 1
 fi
 echo "All URLs found"
